apiVersion: v1
kind: Service
metadata:
  name: senseibird-api
  namespace: senseibird
  labels:
    app: senseibird
    tier: api
spec:
  type: ClusterIP
  selector:
    app: senseibird
    tier: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000

