apiVersion: apps/v1
kind: Deployment
metadata:
  name: senseibird-web-blue
  namespace: senseibird
  labels:
    app: senseibird
    track: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: senseibird
      track: blue
  template:
    metadata:
      labels:
        app: senseibird
        track: blue
    spec:
      containers:
        - name: web
          image: senseibird:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: TRACK
              value: "blue"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://senseibird-api:8000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

