apiVersion: apps/v1
kind: Deployment
metadata:
  name: senseibird-web-green
  namespace: senseibird
  labels:
    app: senseibird
    track: green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: senseibird
      track: green
  template:
    metadata:
      labels:
        app: senseibird
        track: green
    spec:
      containers:
        - name: web
          image: senseibird:green
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_APP_TITLE
              value: "SenseiBird - Aprender Japonés"
            - name: TRACK
              value: "green"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://senseibird-api:8000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
