apiVersion: v1
kind: Service
metadata:
  name: senseibird-svc
  namespace: senseibird
  labels:
    app: senseibird
spec:
  type: NodePort
  selector:
    app: senseibird
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31000   
