{
 "title": "SenseiBird Observability Dashboard",
 "tags": [
  "senseibird",
  "fastapi",
  "devops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SenseiBird API - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Status",
   "type": "stat",
   "description": "Estado UP/DOWN del backend",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"senseibird-api\"}"
    }
   ]
  },
  {
   "title": "Requests per second (RPS)",
   "type": "timeseries",
   "description": "Requests per second (RPS)",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Latencia P95",
   "type": "timeseries",
   "description": "Latencia P95 en segundos",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "Uso de Recursos del Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Uso de CPU del pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"senseibird-api-.*\"}[2m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Uso de memoria del pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"senseibird-api-.*\"}"
    }
   ]
  },
  { "title": "Métrica de Negocio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Actualizaciones de Stats (Métrica de Negocio)",
   "type": "timeseries",
   "description": "Eventos de actualización de stats",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "sum(senseibird_updates_total)" }
   ]
  }
 ]
}